<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Work Experience | Hays Travel</title>
  <link href="/hays.css" rel="stylesheet">
</head>
<body>
  @include('components.nav-bar')
  <div class="content-container">
    <h2 class="independence-title">Hays Travel Independence Group</h2>
    <div class="independence-container">
      <div class="independence-flexbox">
        <img class="benefits-image" src="/haysig2.png">
        <div class="wrapper">
          <p class="independence-description">I first begun at Hays, redesigning their Independence Group website.
            This was my first challenge when it came to my learning of HTML and CSS, the snippet on your screen shows me interacting with
            Bootstrap and understanding how it's components work, developed was an accordion.</p>
        </div>
      </div>
      <div class="independence-flexbox">
        <img class="member-table-image" src="/haysig1.png">
        <div class="wrapper">
          <p class="independence-description-2">Further down the line of this mini project, I began learning about
          how MySQL databases are used within Laravel. The data within the table is all randomly generated by Laravels seeder
          and factories functionality, this makes it easy to fill up a database for testing purposes. This table of data was built within
          an admin panel, which also has the function to edit fields in the data.</p>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
